[build]
  # Build command for React Router
  command = "npm run build"
  
  # Publish directory (React Router build output)
  publish = "build/client"
  
  # Functions directory
  functions = "netlify/functions"
  
  # Edge Functions directory
  edge_functions = "netlify/edge-functions"

[build.environment]
  # Node version
  NODE_VERSION = "20"
  
  # Build environment
  NODE_ENV = "production"

# Redirects for React Router with SSR
[[redirects]]
  # Dynamic movie routes
  from = "/movie/*"
  to = "/index.html"
  status = 200

[[redirects]]
  # All other routes
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache API responses for 5 minutes
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=300"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Headers for dynamic movie routes
[[headers]]
  for = "/movie/*"
  [headers.values]
    Cache-Control = "public, max-age=300"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Production environment variables
[context.production.environment]
  VITE_OMDB_API_KEY = "your_omdb_api_key_here"
  VITE_GA_MEASUREMENT_ID = "your_ga_measurement_id_here"

# Deploy preview environment variables
[context.deploy-preview.environment]
  VITE_OMDB_API_KEY = "your_omdb_api_key_here"
  VITE_GA_MEASUREMENT_ID = "your_ga_measurement_id_here"