[dev]
  # Development server configuration
  command = "npm run dev"
  port = 5173
  publish = "build/client"
  functions = "netlify/functions"

[dev.environment]
  # Development environment variables
  VITE_OMDB_API_KEY = "your_omdb_api_key_here"
  VITE_GA_MEASUREMENT_ID = "your_ga_measurement_id_here"

# Development redirects
[[dev.redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Development headers
[[dev.headers]]
  for = "/*"
  [dev.headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff" 